name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy result to site'
        required: false
        default: 'false'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Install dependencies
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: Test
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: test:unit
    - name: Build for production
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: 'dist'

  
  deploy:
    if: (github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && contains(github.event.head_commit.message, '[deploy]'))
      || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy)

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4